# -------------------------------------------------------------------
spring.application.name=api-gateway
server.port=4444

# Optional Config Server
spring.config.import=optional:configserver:http://localhost:8711


# -------------------------------------------------------------------
# Eureka Client Configuration
# -------------------------------------------------------------------
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.instance.preferIpAddress=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true


# -------------------------------------------------------------------
# JWT Configuration (MUST MATCH auth-service)
# -------------------------------------------------------------------
greengov.security.jwt.secret=hjsgfgfgfasdgaghsgdajgdhasgdahsfdahgsfdhgas


# -------------------------------------------------------------------
# Actuator (useful for Gateway debugging)
# -------------------------------------------------------------------
management.endpoints.web.exposure.include=health,info,gateway


# -------------------------------------------------------------------
# Logging (DEBUG for learning & troubleshooting)
# -------------------------------------------------------------------
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route=TRACE
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty.http.server=DEBUG
logging.level.org.springframework.cloud.client.discovery=DEBUG


# -------------------------------------------------------------------
# Spring Cloud Gateway Routes (WebMVC style)
# -------------------------------------------------------------------
# -------- AUTH SERVICE -----------
spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://auth-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**,/api/admin/**

# -------- PROFILE SERVICE --------
spring.cloud.gateway.server.webmvc.routes[1].id=greengov-profile-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://greengov-profile-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/participants/**
