spring.application.name=greengov-profile-service
server.port=9056


# Disabled for local standalone testing
spring.cloud.config.enabled=false
eureka.client.enabled=false

# The '?createDatabaseIfNotExist=true' does the magic
spring.datasource.url=jdbc:mysql://localhost:3306/greengov_profiles?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect