spring.application.name=GreenGov
 
server.port = 1234
 
#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/GreenGov_Final
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
#hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#JWT
greengov.security.jwt.secret=VGVzdEdyZWVuR292LVN1cGVyLVNlY3JldC1LZXktNjRieXRlcy1iYXNlNjQtc3RyaW5nLXRvLXRlc3Q=
# 7 days
greengov.security.jwt.expiration-minutes=10080


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rohitsingh692004@gmail.com
spring.mail.password=ykap rxhq qghk mnmo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true