spring.application.name=config-server
server.port=8711

#<<<<<<< HEAD
spring.cloud.config.server.git.uri=https://github.com/roxhit/configserver.git

#spring.cloud.config.server.git.uri=https://github.com/Sayan-Maity-Code/ConfigServer.git
#>>>>>>> 176ee72f41bd9470e6f1f48449db4cdf29fc6cdc
spring.cloud.config.server.git.skip-ssl-validation=true
#spring.cloud.config.server.git.uri=https://github.com/Sayan-Maity-Code/ConfigServer.git
#spring.cloud.config.server.git.skip-ssl-validation=true
eureka.client.instance.preferIpAddress = true
eureka.instance.hostname=localhost

